/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as HallOfLegendsRouteImport } from './routes/hall-of-legends'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HallOfLegendsEventIdRouteImport } from './routes/hall-of-legends_.$eventId'
import { Route as ApiRatingsRouteImport } from './routes/api.ratings'
import { Route as AdminHistoryRouteImport } from './routes/admin_.history'
import { Route as ApiEventCurrentRouteImport } from './routes/api.event.current'
import { Route as ApiDraftPickRouteImport } from './routes/api.draft.pick'
import { Route as ApiDraftBidRouteImport } from './routes/api.draft.bid'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthDiscordRouteImport } from './routes/api.auth.discord'
import { Route as ApiAdminResultRouteImport } from './routes/api.admin.result'
import { Route as ApiAdminHistoryRouteImport } from './routes/api.admin.history'
import { Route as ApiAdminEventRouteImport } from './routes/api.admin.event'
import { Route as ApiAdminCoinflipRouteImport } from './routes/api.admin.coinflip'
import { Route as ApiEventCurrentStreamRouteImport } from './routes/api.event.current.stream'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api.auth.discord.callback'
import { Route as ApiAdminTeamsEnsureRouteImport } from './routes/api.admin.teams.ensure'
import { Route as ApiAdminTeamUpdateRouteImport } from './routes/api.admin.team.update'
import { Route as ApiAdminRatingsResetRouteImport } from './routes/api.admin.ratings.reset'
import { Route as ApiAdminRatingsDisqualifyRouteImport } from './routes/api.admin.ratings.disqualify'
import { Route as ApiAdminRaidHelperRefreshRouteImport } from './routes/api.admin.raid-helper.refresh'
import { Route as ApiAdminRaidHelperPostCompositionRouteImport } from './routes/api.admin.raid-helper.post-composition'

const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfLegendsRoute = HallOfLegendsRouteImport.update({
  id: '/hall-of-legends',
  path: '/hall-of-legends',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfLegendsEventIdRoute = HallOfLegendsEventIdRouteImport.update({
  id: '/hall-of-legends_/$eventId',
  path: '/hall-of-legends/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsRoute = ApiRatingsRouteImport.update({
  id: '/api/ratings',
  path: '/api/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin_/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventCurrentRoute = ApiEventCurrentRouteImport.update({
  id: '/api/event/current',
  path: '/api/event/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftPickRoute = ApiDraftPickRouteImport.update({
  id: '/api/draft/pick',
  path: '/api/draft/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftBidRoute = ApiDraftBidRouteImport.update({
  id: '/api/draft/bid',
  path: '/api/draft/bid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResultRoute = ApiAdminResultRouteImport.update({
  id: '/api/admin/result',
  path: '/api/admin/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHistoryRoute = ApiAdminHistoryRouteImport.update({
  id: '/api/admin/history',
  path: '/api/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEventRoute = ApiAdminEventRouteImport.update({
  id: '/api/admin/event',
  path: '/api/admin/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoinflipRoute = ApiAdminCoinflipRouteImport.update({
  id: '/api/admin/coinflip',
  path: '/api/admin/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventCurrentStreamRoute = ApiEventCurrentStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiEventCurrentRoute,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)
const ApiAdminTeamsEnsureRoute = ApiAdminTeamsEnsureRouteImport.update({
  id: '/api/admin/teams/ensure',
  path: '/api/admin/teams/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamUpdateRoute = ApiAdminTeamUpdateRouteImport.update({
  id: '/api/admin/team/update',
  path: '/api/admin/team/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRatingsResetRoute = ApiAdminRatingsResetRouteImport.update({
  id: '/api/admin/ratings/reset',
  path: '/api/admin/ratings/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRatingsDisqualifyRoute =
  ApiAdminRatingsDisqualifyRouteImport.update({
    id: '/api/admin/ratings/disqualify',
    path: '/api/admin/ratings/disqualify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminRaidHelperRefreshRoute =
  ApiAdminRaidHelperRefreshRouteImport.update({
    id: '/api/admin/raid-helper/refresh',
    path: '/api/admin/raid-helper/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminRaidHelperPostCompositionRoute =
  ApiAdminRaidHelperPostCompositionRouteImport.update({
    id: '/api/admin/raid-helper/post-composition',
    path: '/api/admin/raid-helper/post-composition',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draft': typeof DraftRoute
  '/hall-of-legends': typeof HallOfLegendsRoute
  '/overlay': typeof OverlayRoute
  '/ratings': typeof RatingsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/hall-of-legends/$eventId': typeof HallOfLegendsEventIdRoute
  '/api/admin/coinflip': typeof ApiAdminCoinflipRoute
  '/api/admin/event': typeof ApiAdminEventRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/result': typeof ApiAdminResultRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/draft/bid': typeof ApiDraftBidRoute
  '/api/draft/pick': typeof ApiDraftPickRoute
  '/api/event/current': typeof ApiEventCurrentRouteWithChildren
  '/api/admin/raid-helper/post-composition': typeof ApiAdminRaidHelperPostCompositionRoute
  '/api/admin/raid-helper/refresh': typeof ApiAdminRaidHelperRefreshRoute
  '/api/admin/ratings/disqualify': typeof ApiAdminRatingsDisqualifyRoute
  '/api/admin/ratings/reset': typeof ApiAdminRatingsResetRoute
  '/api/admin/team/update': typeof ApiAdminTeamUpdateRoute
  '/api/admin/teams/ensure': typeof ApiAdminTeamsEnsureRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/event/current/stream': typeof ApiEventCurrentStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draft': typeof DraftRoute
  '/hall-of-legends': typeof HallOfLegendsRoute
  '/overlay': typeof OverlayRoute
  '/ratings': typeof RatingsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/hall-of-legends/$eventId': typeof HallOfLegendsEventIdRoute
  '/api/admin/coinflip': typeof ApiAdminCoinflipRoute
  '/api/admin/event': typeof ApiAdminEventRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/result': typeof ApiAdminResultRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/draft/bid': typeof ApiDraftBidRoute
  '/api/draft/pick': typeof ApiDraftPickRoute
  '/api/event/current': typeof ApiEventCurrentRouteWithChildren
  '/api/admin/raid-helper/post-composition': typeof ApiAdminRaidHelperPostCompositionRoute
  '/api/admin/raid-helper/refresh': typeof ApiAdminRaidHelperRefreshRoute
  '/api/admin/ratings/disqualify': typeof ApiAdminRatingsDisqualifyRoute
  '/api/admin/ratings/reset': typeof ApiAdminRatingsResetRoute
  '/api/admin/team/update': typeof ApiAdminTeamUpdateRoute
  '/api/admin/teams/ensure': typeof ApiAdminTeamsEnsureRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/event/current/stream': typeof ApiEventCurrentStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/draft': typeof DraftRoute
  '/hall-of-legends': typeof HallOfLegendsRoute
  '/overlay': typeof OverlayRoute
  '/ratings': typeof RatingsRoute
  '/admin_/history': typeof AdminHistoryRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/hall-of-legends_/$eventId': typeof HallOfLegendsEventIdRoute
  '/api/admin/coinflip': typeof ApiAdminCoinflipRoute
  '/api/admin/event': typeof ApiAdminEventRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/result': typeof ApiAdminResultRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/draft/bid': typeof ApiDraftBidRoute
  '/api/draft/pick': typeof ApiDraftPickRoute
  '/api/event/current': typeof ApiEventCurrentRouteWithChildren
  '/api/admin/raid-helper/post-composition': typeof ApiAdminRaidHelperPostCompositionRoute
  '/api/admin/raid-helper/refresh': typeof ApiAdminRaidHelperRefreshRoute
  '/api/admin/ratings/disqualify': typeof ApiAdminRatingsDisqualifyRoute
  '/api/admin/ratings/reset': typeof ApiAdminRatingsResetRoute
  '/api/admin/team/update': typeof ApiAdminTeamUpdateRoute
  '/api/admin/teams/ensure': typeof ApiAdminTeamsEnsureRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/event/current/stream': typeof ApiEventCurrentStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/draft'
    | '/hall-of-legends'
    | '/overlay'
    | '/ratings'
    | '/admin/history'
    | '/api/ratings'
    | '/hall-of-legends/$eventId'
    | '/api/admin/coinflip'
    | '/api/admin/event'
    | '/api/admin/history'
    | '/api/admin/result'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/draft/bid'
    | '/api/draft/pick'
    | '/api/event/current'
    | '/api/admin/raid-helper/post-composition'
    | '/api/admin/raid-helper/refresh'
    | '/api/admin/ratings/disqualify'
    | '/api/admin/ratings/reset'
    | '/api/admin/team/update'
    | '/api/admin/teams/ensure'
    | '/api/auth/discord/callback'
    | '/api/event/current/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/draft'
    | '/hall-of-legends'
    | '/overlay'
    | '/ratings'
    | '/admin/history'
    | '/api/ratings'
    | '/hall-of-legends/$eventId'
    | '/api/admin/coinflip'
    | '/api/admin/event'
    | '/api/admin/history'
    | '/api/admin/result'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/draft/bid'
    | '/api/draft/pick'
    | '/api/event/current'
    | '/api/admin/raid-helper/post-composition'
    | '/api/admin/raid-helper/refresh'
    | '/api/admin/ratings/disqualify'
    | '/api/admin/ratings/reset'
    | '/api/admin/team/update'
    | '/api/admin/teams/ensure'
    | '/api/auth/discord/callback'
    | '/api/event/current/stream'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/draft'
    | '/hall-of-legends'
    | '/overlay'
    | '/ratings'
    | '/admin_/history'
    | '/api/ratings'
    | '/hall-of-legends_/$eventId'
    | '/api/admin/coinflip'
    | '/api/admin/event'
    | '/api/admin/history'
    | '/api/admin/result'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/draft/bid'
    | '/api/draft/pick'
    | '/api/event/current'
    | '/api/admin/raid-helper/post-composition'
    | '/api/admin/raid-helper/refresh'
    | '/api/admin/ratings/disqualify'
    | '/api/admin/ratings/reset'
    | '/api/admin/team/update'
    | '/api/admin/teams/ensure'
    | '/api/auth/discord/callback'
    | '/api/event/current/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DraftRoute: typeof DraftRoute
  HallOfLegendsRoute: typeof HallOfLegendsRoute
  OverlayRoute: typeof OverlayRoute
  RatingsRoute: typeof RatingsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  ApiRatingsRoute: typeof ApiRatingsRoute
  HallOfLegendsEventIdRoute: typeof HallOfLegendsEventIdRoute
  ApiAdminCoinflipRoute: typeof ApiAdminCoinflipRoute
  ApiAdminEventRoute: typeof ApiAdminEventRoute
  ApiAdminHistoryRoute: typeof ApiAdminHistoryRoute
  ApiAdminResultRoute: typeof ApiAdminResultRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiDraftBidRoute: typeof ApiDraftBidRoute
  ApiDraftPickRoute: typeof ApiDraftPickRoute
  ApiEventCurrentRoute: typeof ApiEventCurrentRouteWithChildren
  ApiAdminRaidHelperPostCompositionRoute: typeof ApiAdminRaidHelperPostCompositionRoute
  ApiAdminRaidHelperRefreshRoute: typeof ApiAdminRaidHelperRefreshRoute
  ApiAdminRatingsDisqualifyRoute: typeof ApiAdminRatingsDisqualifyRoute
  ApiAdminRatingsResetRoute: typeof ApiAdminRatingsResetRoute
  ApiAdminTeamUpdateRoute: typeof ApiAdminTeamUpdateRoute
  ApiAdminTeamsEnsureRoute: typeof ApiAdminTeamsEnsureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-legends': {
      id: '/hall-of-legends'
      path: '/hall-of-legends'
      fullPath: '/hall-of-legends'
      preLoaderRoute: typeof HallOfLegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-legends_/$eventId': {
      id: '/hall-of-legends_/$eventId'
      path: '/hall-of-legends/$eventId'
      fullPath: '/hall-of-legends/$eventId'
      preLoaderRoute: typeof HallOfLegendsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings': {
      id: '/api/ratings'
      path: '/api/ratings'
      fullPath: '/api/ratings'
      preLoaderRoute: typeof ApiRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/history': {
      id: '/admin_/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event/current': {
      id: '/api/event/current'
      path: '/api/event/current'
      fullPath: '/api/event/current'
      preLoaderRoute: typeof ApiEventCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft/pick': {
      id: '/api/draft/pick'
      path: '/api/draft/pick'
      fullPath: '/api/draft/pick'
      preLoaderRoute: typeof ApiDraftPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft/bid': {
      id: '/api/draft/bid'
      path: '/api/draft/bid'
      fullPath: '/api/draft/bid'
      preLoaderRoute: typeof ApiDraftBidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/result': {
      id: '/api/admin/result'
      path: '/api/admin/result'
      fullPath: '/api/admin/result'
      preLoaderRoute: typeof ApiAdminResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/history': {
      id: '/api/admin/history'
      path: '/api/admin/history'
      fullPath: '/api/admin/history'
      preLoaderRoute: typeof ApiAdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/event': {
      id: '/api/admin/event'
      path: '/api/admin/event'
      fullPath: '/api/admin/event'
      preLoaderRoute: typeof ApiAdminEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/coinflip': {
      id: '/api/admin/coinflip'
      path: '/api/admin/coinflip'
      fullPath: '/api/admin/coinflip'
      preLoaderRoute: typeof ApiAdminCoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event/current/stream': {
      id: '/api/event/current/stream'
      path: '/stream'
      fullPath: '/api/event/current/stream'
      preLoaderRoute: typeof ApiEventCurrentStreamRouteImport
      parentRoute: typeof ApiEventCurrentRoute
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
    '/api/admin/teams/ensure': {
      id: '/api/admin/teams/ensure'
      path: '/api/admin/teams/ensure'
      fullPath: '/api/admin/teams/ensure'
      preLoaderRoute: typeof ApiAdminTeamsEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/team/update': {
      id: '/api/admin/team/update'
      path: '/api/admin/team/update'
      fullPath: '/api/admin/team/update'
      preLoaderRoute: typeof ApiAdminTeamUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ratings/reset': {
      id: '/api/admin/ratings/reset'
      path: '/api/admin/ratings/reset'
      fullPath: '/api/admin/ratings/reset'
      preLoaderRoute: typeof ApiAdminRatingsResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ratings/disqualify': {
      id: '/api/admin/ratings/disqualify'
      path: '/api/admin/ratings/disqualify'
      fullPath: '/api/admin/ratings/disqualify'
      preLoaderRoute: typeof ApiAdminRatingsDisqualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/raid-helper/refresh': {
      id: '/api/admin/raid-helper/refresh'
      path: '/api/admin/raid-helper/refresh'
      fullPath: '/api/admin/raid-helper/refresh'
      preLoaderRoute: typeof ApiAdminRaidHelperRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/raid-helper/post-composition': {
      id: '/api/admin/raid-helper/post-composition'
      path: '/api/admin/raid-helper/post-composition'
      fullPath: '/api/admin/raid-helper/post-composition'
      preLoaderRoute: typeof ApiAdminRaidHelperPostCompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

interface ApiEventCurrentRouteChildren {
  ApiEventCurrentStreamRoute: typeof ApiEventCurrentStreamRoute
}

const ApiEventCurrentRouteChildren: ApiEventCurrentRouteChildren = {
  ApiEventCurrentStreamRoute: ApiEventCurrentStreamRoute,
}

const ApiEventCurrentRouteWithChildren = ApiEventCurrentRoute._addFileChildren(
  ApiEventCurrentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DraftRoute: DraftRoute,
  HallOfLegendsRoute: HallOfLegendsRoute,
  OverlayRoute: OverlayRoute,
  RatingsRoute: RatingsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  ApiRatingsRoute: ApiRatingsRoute,
  HallOfLegendsEventIdRoute: HallOfLegendsEventIdRoute,
  ApiAdminCoinflipRoute: ApiAdminCoinflipRoute,
  ApiAdminEventRoute: ApiAdminEventRoute,
  ApiAdminHistoryRoute: ApiAdminHistoryRoute,
  ApiAdminResultRoute: ApiAdminResultRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiDraftBidRoute: ApiDraftBidRoute,
  ApiDraftPickRoute: ApiDraftPickRoute,
  ApiEventCurrentRoute: ApiEventCurrentRouteWithChildren,
  ApiAdminRaidHelperPostCompositionRoute:
    ApiAdminRaidHelperPostCompositionRoute,
  ApiAdminRaidHelperRefreshRoute: ApiAdminRaidHelperRefreshRoute,
  ApiAdminRatingsDisqualifyRoute: ApiAdminRatingsDisqualifyRoute,
  ApiAdminRatingsResetRoute: ApiAdminRatingsResetRoute,
  ApiAdminTeamUpdateRoute: ApiAdminTeamUpdateRoute,
  ApiAdminTeamsEnsureRoute: ApiAdminTeamsEnsureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
